<a href="https://colab.research.google.com/github/hnihtt/ThucHanhToanCC/blob/main/bai5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Thực hành 1:

In [2]:
import math

In [1]:
x = 3
print(x)

3


In [3]:
x = math.sqrt(1+x)
print(x)

2.0


In [5]:
x = math.sqrt(1+x)
print(x)

1.6528916502810695


In [6]:
x = math.sqrt(1+x)
print(x)

1.6287699807772333


In [7]:
x = math.sqrt(1+x)
print(x)

1.621348198499395


In [8]:
x = math.sqrt(1+x)
print(x)

1.6190578119694785


In [9]:
x = math.sqrt(1+x)
print(x)

1.618350336598809


In [10]:
x = math.sqrt(1+x)
print(x)

1.6181317426584303


#Thực hành 2:

In [12]:
import math
x = 3
lap = 1
while (x != math.sqrt(x+1)):
  x = math.sqrt(x+1)
  lap += 1

In [13]:
x

1.618033988749895

In [14]:
lap

32

#Thực hành 3: 

In [15]:
import sympy as sp 
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x)

[1/2 + sqrt(5)/2]

#Thực hành 4:


In [20]:
import numpy as np
v1 = np.array([1.,2.,3.])
v2 = np.array([2.,1.,0.])
#cộng vector:
v3 = v1 + v2
v3


array([3., 3., 3.])

In [17]:
3*v1 + 2*v2

array([7., 8., 9.])

In [18]:
#numpy.array khác với kiểu dữ liệu list:
[1,2,3] + [2,1,0]

[1, 2, 3, 2, 1, 0]

In [19]:
3*[1,2,3] + 2*[2,1,0]

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [22]:
#ghép nối (Concatenating) 2 hoặc nhiều vector:
v4 = np.hstack([v1,v2])
v4

array([1., 2., 3., 2., 1., 0.])

In [25]:
#phép nhân vô hướng 2 vector:
np.dot(v1,v2)

4.0

In [26]:
#tính giá trị sin của vector:
angles = np.linspace(0,np.pi/2,5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [27]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])